apiVersion: apps/v1
kind: Deployment
metadata:
  name: nagp-voting-app
  namespace: nagp
  labels:
    app: nagp-voting-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nagp-voting-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: nagp-voting-app
    spec:
      containers:
        - name: nagp-voting-app
          image: mohammadehtesham/nagp-voting:1.0.1
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: nagp-voting-app-secret
            - configMapRef:
                name: nagp-voting-app-config
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 150
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 150
            periodSeconds: 10