apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nagp-hpa
  namespace: nagp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nagp-voting-app
  minReplicas: 3
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 10
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30
      policies:
      - type: Percent
        value: 80
        periodSeconds: 60  
    scaleUp:
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30 